/**
 * @fileoverview Runtime allocator WAT helpers (size classes + free lists).
 * Modeled after AssemblyScript's allocator: size classes, bump pointer, freelists.
 */

import { buildFunction, param, local, i32Const } from './wat.js';

const CLASS_SIZES = [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096];

/**
 * Build allocator globals and functions.
 * @returns {{ globals: string[], functions: string[] }}
 */
export function buildAllocator() {
  const globals = [
    '(global $__jswat_bump (mut i32) (i32.const 1024))',
    '(global $__jswat_fl_0 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_1 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_2 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_3 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_4 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_5 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_6 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_7 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_8 (mut i32) (i32.const 0))',
    '(global $__jswat_fl_9 (mut i32) (i32.const 0))',
  ];

  const allocFn = buildFunction({
    name: '__jswat_alloc',
    export: '__jswat_alloc',
    params: [param('size', 'i32')],
    result: 'i32',
    locals: [
      local('rounded', 'i32'),
      local('classSize', 'i32'),
      local('classIndex', 'i32'),
      local('head', 'i32'),
      local('next', 'i32'),
      local('ptr', 'i32'),
      local('newBump', 'i32'),
      local('mem', 'i32'),
      local('pages', 'i32'),
    ],
    body: [
      // round up to 8 bytes
      'local.get $size',
      i32Const(7),
      'i32.add',
      i32Const(-8),
      'i32.and',
      'local.set $rounded',

      // pick size class
      'local.get $rounded',
      i32Const(CLASS_SIZES[0]),
      'i32.le_u',
      'if',
      `  ${i32Const(CLASS_SIZES[0])}`,
      '  local.set $classSize',
      i32Const(0),
      '  local.set $classIndex',
      'else',
      '  local.get $rounded',
      i32Const(CLASS_SIZES[1]),
      '  i32.le_u',
      '  if',
      `    ${i32Const(CLASS_SIZES[1])}`,
      '    local.set $classSize',
      i32Const(1),
      '    local.set $classIndex',
      '  else',
      '    local.get $rounded',
      i32Const(CLASS_SIZES[2]),
      '    i32.le_u',
      '    if',
      `      ${i32Const(CLASS_SIZES[2])}`,
      '      local.set $classSize',
      i32Const(2),
      '      local.set $classIndex',
      '    else',
      '      local.get $rounded',
      i32Const(CLASS_SIZES[3]),
      '      i32.le_u',
      '      if',
      `        ${i32Const(CLASS_SIZES[3])}`,
      '        local.set $classSize',
      i32Const(3),
      '        local.set $classIndex',
      '      else',
      '        local.get $rounded',
      i32Const(CLASS_SIZES[4]),
      '        i32.le_u',
      '        if',
      `          ${i32Const(CLASS_SIZES[4])}`,
      '          local.set $classSize',
      i32Const(4),
      '          local.set $classIndex',
      '        else',
      '          local.get $rounded',
      i32Const(CLASS_SIZES[5]),
      '          i32.le_u',
      '          if',
      `            ${i32Const(CLASS_SIZES[5])}`,
      '            local.set $classSize',
      i32Const(5),
      '            local.set $classIndex',
      '          else',
      '            local.get $rounded',
      i32Const(CLASS_SIZES[6]),
      '            i32.le_u',
      '            if',
      `              ${i32Const(CLASS_SIZES[6])}`,
      '              local.set $classSize',
      i32Const(6),
      '              local.set $classIndex',
      '            else',
      '              local.get $rounded',
      i32Const(CLASS_SIZES[7]),
      '              i32.le_u',
      '              if',
      `                ${i32Const(CLASS_SIZES[7])}`,
      '                local.set $classSize',
      i32Const(7),
      '                local.set $classIndex',
      '              else',
      '                local.get $rounded',
      i32Const(CLASS_SIZES[8]),
      '                i32.le_u',
      '                if',
      `                  ${i32Const(CLASS_SIZES[8])}`,
      '                  local.set $classSize',
      i32Const(8),
      '                  local.set $classIndex',
      '                else',
      '                  local.get $rounded',
      i32Const(CLASS_SIZES[9]),
      '                  i32.le_u',
      '                  if',
      `                    ${i32Const(CLASS_SIZES[9])}`,
      '                    local.set $classSize',
      i32Const(9),
      '                    local.set $classIndex',
      '                  else',
      '                    local.get $rounded',
      '                    local.set $classSize',
      i32Const(10),
      '                    local.set $classIndex',
      '                  end',
      '                end',
      '              end',
      '            end',
      '          end',
      '        end',
      '      end',
      '    end',
      '  end',
      'end',

      // small class: try free list
      'block $bump',
      '  local.get $classIndex',
      i32Const(9),
      '  i32.le_u',
      '  if',
      '    local.get $classIndex',
      '    i32.const 0',
      '    i32.eq',
      '    if',
      '      global.get $__jswat_fl_0',
      '      local.set $head',
      '    else',
      '      local.get $classIndex',
      '      i32.const 1',
      '      i32.eq',
      '      if',
      '        global.get $__jswat_fl_1',
      '        local.set $head',
      '      else',
      '        local.get $classIndex',
      '        i32.const 2',
      '        i32.eq',
      '        if',
      '          global.get $__jswat_fl_2',
      '          local.set $head',
      '        else',
      '          local.get $classIndex',
      '          i32.const 3',
      '          i32.eq',
      '          if',
      '            global.get $__jswat_fl_3',
      '            local.set $head',
      '          else',
      '            local.get $classIndex',
      '            i32.const 4',
      '            i32.eq',
      '            if',
      '              global.get $__jswat_fl_4',
      '              local.set $head',
      '            else',
      '              local.get $classIndex',
      '              i32.const 5',
      '              i32.eq',
      '              if',
      '                global.get $__jswat_fl_5',
      '                local.set $head',
      '              else',
      '                local.get $classIndex',
      '                i32.const 6',
      '                i32.eq',
      '                if',
      '                  global.get $__jswat_fl_6',
      '                  local.set $head',
      '                else',
      '                  local.get $classIndex',
      '                  i32.const 7',
      '                  i32.eq',
      '                  if',
      '                    global.get $__jswat_fl_7',
      '                    local.set $head',
      '                  else',
      '                    local.get $classIndex',
      '                    i32.const 8',
      '                    i32.eq',
      '                    if',
      '                      global.get $__jswat_fl_8',
      '                      local.set $head',
      '                    else',
      '                      global.get $__jswat_fl_9',
      '                      local.set $head',
      '                    end',
      '                  end',
      '                end',
      '              end',
      '            end',
      '          end',
      '        end',
      '      end',
      '    end',
      '    local.get $head',
      '    i32.eqz',
      '    br_if $bump',
      '    local.get $head',
      '    i32.load',
      '    local.set $next',
      '    local.get $classIndex',
      '    i32.const 0',
      '    i32.eq',
      '    if',
      '      local.get $next',
      '      global.set $__jswat_fl_0',
      '    else',
      '      local.get $classIndex',
      '      i32.const 1',
      '      i32.eq',
      '      if',
      '        local.get $next',
      '        global.set $__jswat_fl_1',
      '      else',
      '        local.get $classIndex',
      '        i32.const 2',
      '        i32.eq',
      '        if',
      '          local.get $next',
      '          global.set $__jswat_fl_2',
      '        else',
      '          local.get $classIndex',
      '          i32.const 3',
      '          i32.eq',
      '          if',
      '            local.get $next',
      '            global.set $__jswat_fl_3',
      '          else',
      '            local.get $classIndex',
      '            i32.const 4',
      '            i32.eq',
      '            if',
      '              local.get $next',
      '              global.set $__jswat_fl_4',
      '            else',
      '              local.get $classIndex',
      '              i32.const 5',
      '              i32.eq',
      '              if',
      '                local.get $next',
      '                global.set $__jswat_fl_5',
      '              else',
      '                local.get $classIndex',
      '                i32.const 6',
      '                i32.eq',
      '                if',
      '                  local.get $next',
      '                  global.set $__jswat_fl_6',
      '                else',
      '                  local.get $classIndex',
      '                  i32.const 7',
      '                  i32.eq',
      '                  if',
      '                    local.get $next',
      '                    global.set $__jswat_fl_7',
      '                  else',
      '                    local.get $classIndex',
      '                    i32.const 8',
      '                    i32.eq',
      '                    if',
      '                      local.get $next',
      '                      global.set $__jswat_fl_8',
      '                    else',
      '                      local.get $next',
      '                      global.set $__jswat_fl_9',
      '                    end',
      '                  end',
      '                end',
      '              end',
      '            end',
      '          end',
      '        end',
      '      end',
      '    end',
      '    local.get $head',
      i32Const(-1),
      '    i32.store',
      '    local.get $head',
      '    return',
      '  end',
      'end',

      // bump allocation
      'global.get $__jswat_bump',
      'local.set $ptr',
      'local.get $ptr',
      'local.get $classSize',
      'i32.add',
      'local.set $newBump',
      'memory.size',
      i32Const(65536),
      'i32.mul',
      'local.set $mem',
      'local.get $newBump',
      'local.get $mem',
      'i32.gt_u',
      'if',
      '  local.get $newBump',
      '  local.get $mem',
      '  i32.sub',
      i32Const(65535),
      '  i32.add',
      i32Const(65536),
      '  i32.div_u',
      '  local.set $pages',
      '  local.get $pages',
      '  memory.grow',
      i32Const(-1),
      '  i32.eq',
      '  if',
      '    unreachable',
      '  end',
      'end',
      'local.get $newBump',
      'global.set $__jswat_bump',
      'local.get $ptr',
      i32Const(-1),
      'i32.store',
      'local.get $ptr',
    ],
  });

  const freeFn = buildFunction({
    name: '__jswat_free',
    export: '__jswat_free',
    params: [param('ptr', 'i32'), param('size', 'i32')],
    result: '',
    locals: [
      local('rounded', 'i32'),
      local('classIndex', 'i32'),
    ],
    body: [
      'local.get $ptr',
      'i32.eqz',
      'if',
      '  return',
      'end',
      'local.get $size',
      i32Const(7),
      'i32.add',
      i32Const(-8),
      'i32.and',
      'local.set $rounded',
      'local.get $rounded',
      i32Const(CLASS_SIZES[0]),
      'i32.le_u',
      'if',
      i32Const(0),
      '  local.set $classIndex',
      'else',
      '  local.get $rounded',
      i32Const(CLASS_SIZES[1]),
      '  i32.le_u',
      '  if',
      i32Const(1),
      '    local.set $classIndex',
      '  else',
      '    local.get $rounded',
      i32Const(CLASS_SIZES[2]),
      '    i32.le_u',
      '    if',
      i32Const(2),
      '      local.set $classIndex',
      '    else',
      '      local.get $rounded',
      i32Const(CLASS_SIZES[3]),
      '      i32.le_u',
      '      if',
      i32Const(3),
      '        local.set $classIndex',
      '      else',
      '        local.get $rounded',
      i32Const(CLASS_SIZES[4]),
      '        i32.le_u',
      '        if',
      i32Const(4),
      '          local.set $classIndex',
      '        else',
      '          local.get $rounded',
      i32Const(CLASS_SIZES[5]),
      '          i32.le_u',
      '          if',
      i32Const(5),
      '            local.set $classIndex',
      '          else',
      '            local.get $rounded',
      i32Const(CLASS_SIZES[6]),
      '            i32.le_u',
      '            if',
      i32Const(6),
      '              local.set $classIndex',
      '            else',
      '              local.get $rounded',
      i32Const(CLASS_SIZES[7]),
      '              i32.le_u',
      '              if',
      i32Const(7),
      '                local.set $classIndex',
      '              else',
      '                local.get $rounded',
      i32Const(CLASS_SIZES[8]),
      '                i32.le_u',
      '                if',
      i32Const(8),
      '                  local.set $classIndex',
      '                else',
      '                  local.get $rounded',
      i32Const(CLASS_SIZES[9]),
      '                  i32.le_u',
      '                  if',
      i32Const(9),
      '                    local.set $classIndex',
      '                  else',
      '                    return',
      '                  end',
      '                end',
      '              end',
      '            end',
      '          end',
      '        end',
      '      end',
      '    end',
      '  end',
      'end',

      'local.get $classIndex',
      'i32.const 0',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_0',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_0',
      '  return',
      'end',
      'local.get $classIndex',
      'i32.const 1',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_1',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_1',
      '  return',
      'end',
      'local.get $classIndex',
      'i32.const 2',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_2',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_2',
      '  return',
      'end',
      'local.get $classIndex',
      'i32.const 3',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_3',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_3',
      '  return',
      'end',
      'local.get $classIndex',
      'i32.const 4',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_4',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_4',
      '  return',
      'end',
      'local.get $classIndex',
      'i32.const 5',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_5',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_5',
      '  return',
      'end',
      'local.get $classIndex',
      'i32.const 6',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_6',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_6',
      '  return',
      'end',
      'local.get $classIndex',
      'i32.const 7',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_7',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_7',
      '  return',
      'end',
      'local.get $classIndex',
      'i32.const 8',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  global.get $__jswat_fl_8',
      '  i32.store',
      '  local.get $ptr',
      '  global.set $__jswat_fl_8',
      '  return',
      'end',
      'local.get $ptr',
      'global.get $__jswat_fl_9',
      'i32.store',
      'local.get $ptr',
      'global.set $__jswat_fl_9',
    ],
  });

  const allocBytesFn = buildFunction({
    name: '__jswat_alloc_bytes',
    export: '__jswat_alloc_bytes',
    params: [param('n', 'i32'), param('fill', 'i32')],
    result: 'i32',
    locals: [local('ptr', 'i32'), local('size', 'i32')],
    body: [
      'local.get $n',
      i32Const(4),
      'i32.add',
      'local.set $size',
      'local.get $size',
      'call $__jswat_alloc',
      'local.tee $ptr',
      i32Const(4),
      'i32.add',
      'local.get $fill',
      'local.get $n',
      'memory.fill',
      'local.get $ptr',
      i32Const(4),
      'i32.add',
    ],
  });

  const freeBytesFn = buildFunction({
    name: '__jswat_free_bytes',
    export: '__jswat_free_bytes',
    params: [param('ptr', 'i32'), param('n', 'i32')],
    result: '',
    locals: [local('hdr', 'i32'), local('size', 'i32')],
    body: [
      'local.get $ptr',
      i32Const(4),
      'i32.sub',
      'local.set $hdr',
      'local.get $n',
      i32Const(4),
      'i32.add',
      'local.set $size',
      'local.get $hdr',
      'local.get $size',
      'call $__jswat_free',
    ],
  });

  const reallocFn = buildFunction({
    name: '__jswat_realloc',
    export: '__jswat_realloc',
    params: [param('ptr', 'i32'), param('oldSize', 'i32'), param('newSize', 'i32')],
    result: 'i32',
    locals: [local('newPtr', 'i32'), local('copyLen', 'i32')],
    body: [
      'local.get $newSize',
      'local.get $oldSize',
      'i32.eq',
      'if',
      '  local.get $ptr',
      '  return',
      'end',
      'local.get $newSize',
      i32Const(0),
      'call $__jswat_alloc_bytes',
      'local.set $newPtr',
      'local.get $oldSize',
      'local.get $newSize',
      'i32.lt_u',
      'if',
      '  local.get $oldSize',
      '  local.set $copyLen',
      'else',
      '  local.get $newSize',
      '  local.set $copyLen',
      'end',
      'local.get $newPtr',
      'local.get $ptr',
      'local.get $copyLen',
      'memory.copy',
      'local.get $ptr',
      'local.get $oldSize',
      'call $__jswat_free_bytes',
      'local.get $newPtr',
    ],
  });

  const allocWrapper = buildFunction({
    name: '__alloc',
    export: '__alloc',
    params: [param('size', 'i32')],
    result: 'i32',
    body: ['local.get $size', 'call $__jswat_alloc'],
  });

  const freeWrapper = buildFunction({
    name: '__free',
    export: '__free',
    params: [param('ptr', 'i32'), param('size', 'i32')],
    result: '',
    body: ['local.get $ptr', 'local.get $size', 'call $__jswat_free'],
  });

  return {
    globals,
    functions: [allocFn, freeFn, allocBytesFn, freeBytesFn, reallocFn, allocWrapper, freeWrapper],
  };
}
